### ISSUE TITLE
change errorlevel when it can't compile

### ISSUE THREAD

**Issue by Kreijstal** [jumanji144/Jasm#14]
do not return 0 (OK) when there is a compile error.
![image](https://github.com/jumanji144/Jasm/assets/2415206/e737c41a-2499-497c-97fa-b11d8e8b65fd)
This makes it harder to script. Thanks for your awesome project.

**Comment by jumanji144** [comment]
Fixed in 61f5f580c1652fae66de0c6b9c869c70ffb4165a
